In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("./SVM_Dataset_Glass.csv")
df.head()

Id       RI     Na    Mg    Al    Si      K    Ca   Ba   Fe  Type
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [4]:
# Creating a numpy array X conatining 6 rows and 2 coloumns. Each row is a sample and coloums a feature. Y is the label for these samples

X=np.array([[3,4],[1,4],[2,3],[6,-1],[7,-1],[5,-3]])
y=np.array([-1,-1,-1,1,1,1])

In [5]:
# Creating an SVM model. Value 'C' is the penality of misclassfication. So the higher it is the lesser the chance of misclassification.

from sklearn.svm import SVC

model = SVC(C=1e5, kernel='linear')
model.fit(X, y)

SVC(C=100000.0, kernel='linear')

In [6]:
# Printing the attributes of the SVM Classifier

print("coef_: the weights assigned to each feature in the decision function", model.coef_)
print("intercept_: the bias term in the decision function", model.intercept_)
print("support_: the indices of the support vectors in the training set", model.support_)
print("support_vectors_: the support vectors themselves", model.support_vectors_)
print("n_support_: the number of support vectors from each class", model.n_support_)
print(" dual_coef_: the coefficients of the support vectors in the decision function", model.dual_coef_)


coef_: the weights assigned to each feature in the decision function [[ 0.25 -0.25]]
intercept_: the bias term in the decision function [-0.75]
support_: the indices of the support vectors in the training set [2 3]
support_vectors_: the support vectors themselves [[ 2.  3.]
 [ 6. -1.]]
n_support_: the number of support vectors from each class [1 1]
 dual_coef_: the coefficients of the support vectors in the decision function [[-0.0625  0.0625]]


In [7]:
df = pd.read_csv("./SVM_Dataset_Glass.csv")
df.head()

Id       RI     Na    Mg    Al    Si      K    Ca   Ba   Fe  Type
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [13]:
# Extracting the input features x and the labels y
x = df.drop('Type', axis = 1)
y = df['Type']

In [16]:
from sklearn.model_selection import train_test_split

# Splitting into training and testing dataset
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [17]:
# Creating an SVM model

model = SVC(kernel='linear')
model.fit(x_train, y_train)

SVC(kernel='linear')

In [18]:
print(model.support_vectors_)

[[6.90000e+01 1.52152e+00 1.31200e+01 3.58000e+00 9.00000e-01 7.22000e+01
  2.30000e-01 9.82000e+00 0.00000e+00 1.60000e-01]
 [1.45000e+02 1.51660e+00 1.29900e+01 3.18000e+00 1.23000e+00 7.29700e+01
  5.80000e-01 8.81000e+00 0.00000e+00 2.40000e-01]
 [7.10000e+01 1.51574e+00 1.48600e+01 3.67000e+00 1.74000e+00 7.18700e+01
  1.60000e-01 7.36000e+00 0.00000e+00 1.20000e-01]
 [7.20000e+01 1.51848e+00 1.36400e+01 3.87000e+00 1.27000e+00 7.19600e+01
  5.40000e-01 8.32000e+00 0.00000e+00 3.20000e-01]
 [1.48000e+02 1.51610e+00 1.33300e+01 3.53000e+00 1.34000e+00 7.26700e+01
  5.60000e-01 8.33000e+00 0.00000e+00 0.00000e+00]
 [1.63000e+02 1.52211e+00 1.41900e+01 3.78000e+00 9.10000e-01 7.13600e+01
  2.30000e-01 9.14000e+00 0.00000e+00 3.70000e-01]
 [1.66000e+02 1.52171e+00 1.15600e+01 1.88000e+00 1.56000e+00 7.28600e+01
  4.70000e-01 1.14100e+01 0.00000e+00 0.00000e+00]
 [1.75000e+02 1.52058e+00 1.28500e+01 1.61000e+00 2.17000e+00 7.21800e+01
  7.60000e-01 9.70000e+00 2.40000e-01 5.10000e-01]


In [19]:
# Making predictions using the trained model
y_pred = model.predict(x_test)

In [20]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Printing the accurace, confusion matrix and classification report

print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

1.0
[[20  0  0  0  0  0]
 [ 0 25  0  0  0  0]
 [ 0  0  5  0  0  0]
 [ 0  0  0  5  0  0]
 [ 0  0  0  0  4  0]
 [ 0  0  0  0  0  6]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        20
           2       1.00      1.00      1.00        25
           3       1.00      1.00      1.00         5
           5       1.00      1.00      1.00         5
           6       1.00      1.00      1.00         4
           7       1.00      1.00      1.00         6

    accuracy                           1.00        65
   macro avg       1.00      1.00      1.00        65
weighted avg       1.00      1.00      1.00        65



In [21]:
# Training and testing with diffrent kernals and finding the accuracy etc.

model1 = SVC(kernel='sigmoid', gamma=0.001)
model2 = SVC(kernel='poly', degree=3)
model3 = SVC(kernel='rbf')

In [22]:
model1.fit(x_train, y_train)
model2.fit(x_train, y_train)
model3.fit(x_train, y_train)

SVC()

In [23]:
y_pred1 = model1.predict(x_test)
y_pred2 = model2.predict(x_test)
y_pred3 = model3.predict(x_test)

In [24]:
# Printing their accuracy scores

print(accuracy_score(y_test, y_pred1))
print(accuracy_score(y_test, y_pred2))
print(accuracy_score(y_test, y_pred3))

0.38461538461538464
0.9230769230769231
0.8153846153846154
