In [1]:
import pandas as pd
import numpy as np

In [3]:
# Creating a numpy array X conatining 6 rows and 2 coloumns. Each row is a sample and coloums a feature. Y is the label for these samples

x=np.array([[3,4],[1,4],[2,3],[6,-1],[7,-1],[5,-3]])
y=np.array([-1,-1,-1,1,1,1])

# cereating a classification model
from sklearn.svm import SVC
model = SVC(kernel="linear")

model.fit(x, y)

SVC(kernel='linear')

In [5]:
# printing the properties of the svm
print(model.coef_)
print(model.support_)
print(model.support_vectors_)
print(model.dual_coef_)

[[ 0.25 -0.25]]
[2 3]
[[ 2.  3.]
 [ 6. -1.]]
[[-0.0625  0.0625]]


In [6]:
# importing data and creating dataframe x and y
df = pd.read_csv("./SVM_Dataset_Glass.csv")
df.head()

Id       RI     Na    Mg    Al    Si      K    Ca   Ba   Fe  Type
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [10]:
x = df.drop("Type", axis=1)
y = df["Type"]

In [11]:
# creating test and training data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [13]:
# creating linar svm model and training it
model1 = SVC(kernel="linear")

model1.fit(x_train, y_train)
y_pred1 = model1.predict(x_test)

In [15]:
# printing the accuracy score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("linear model accuracy : ", accuracy_score(y_test, y_pred1))
print(confusion_matrix(y_test, y_pred1))
print(classification_report(y_test, y_pred1))

linear model accuracy :  1.0
[[17  0  0  0  0  0]
 [ 0 15  0  0  0  0]
 [ 0  0  3  0  0  0]
 [ 0  0  0  2  0  0]
 [ 0  0  0  0  1  0]
 [ 0  0  0  0  0  5]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        17
           2       1.00      1.00      1.00        15
           3       1.00      1.00      1.00         3
           5       1.00      1.00      1.00         2
           6       1.00      1.00      1.00         1
           7       1.00      1.00      1.00         5

    accuracy                           1.00        43
   macro avg       1.00      1.00      1.00        43
weighted avg       1.00      1.00      1.00        43



In [20]:
# creating models for rbf, polynomial and sigmoid and training them and predicting the values
model2 = SVC(kernel="rbf")
model3 = SVC(kernel="poly")
model4 = SVC(kernel="rbf")

model2.fit(x_train, y_train)
model3.fit(x_train, y_train)
model4.fit(x_train, y_train)

y_pred2 = model2.predict(x_test)
y_pred3 = model3.predict(x_test)
y_pred4 = model4.predict(x_test)

In [21]:
# prting their induvidual accuracies
print(accuracy_score(y_test, y_pred2))
print(accuracy_score(y_test, y_pred3))
print(accuracy_score(y_test, y_pred4))

0.8837209302325582
0.9767441860465116
0.8837209302325582
